apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-rca
spec:
  replicas: 3
  selector:
    app: kubia-poa
  template:
    metadata:
      labels:
        app: kubia-poa
    spec:
      containers:
      - name: kubia-pob
        image: rkotari/kubia
        readinessProbe:
          exec:
            command:
            - ls
            - /var/ready
        ports:
        - containerPort: 8080